- src/shared/en/aws/guides-offline.md
These tests would throw errors as written. Now they do not.
> Update http tests for Working Locally Tutorial

- src/shared/en/aws/guides-static-assets.md
The example `let html ...` code is missing an equals sign. Without it, the example code isn't valid.
> `=` sign missing in code example

- src/shared/en/aws/guides-static-assets.md
- src/shared/en/aws/reference-static.md
FYI @brianleroux 
I think similar to the discussion that was had in #50, this could probably use some more work and reasoning behind what kind of content to put in the CLI help docs vs. the `npx deploy` arc.codes guide vs. the Static Assets arc.codes guide.
> 📝 documenting the --delete static deploy flag

- src/shared/render.js
The intention of the GitHub link is to get people to contribute to, or fix, the docs right? So the GitHub link should go the docs (in `arc.codes` repo), not to architect (in `architect` repo).
> Make GitHub link in arc docs point to arc docs

- src/shared/en/aws/_nav.md
- src/shared/en/aws/guides-background-tasks.md
- src/shared/en/aws/guides-data.md
- src/shared/en/aws/guides-http.md
- src/shared/en/aws/guides-middleware.md
- src/shared/en/aws/guides-sessions.md
- src/shared/en/aws/guides-static-assets.md
- src/shared/en/aws/guides-urls.md
- src/shared/en/aws/quickstart-arc-project-layout.md
- src/shared/en/aws/quickstart-what-next.md
- Add 'what next' to quickstart linking to the various tutorials
- Add 'background tasks' guide
- Move/consolidate the docs in `http` for `sessions`, `middleware` etc into their respective guides, making `http` a lot smaller and using links to the various guides.
Fixes #77
> Add 'what next' to quickstart

- src/shared/en/aws/guides-middleware.md
Since 'context' has a specific meaning for lambda
> Avoid overloading 'context'

- src/shared/en/aws/guides-middleware.md
Chrome caches 301 redirects which can lead to very confusing middleware route debugging, in addition to which a hard site refresh in incognito mode doesn't clear the 301 cache...
> Change 301 to 302 in middleware example

- public/reference/functions/tables/node.md
Noticed there were still some references to the @architect/data module that was deprecated in v6. I'm new to @architect, and I didn't check to make sure that any of these work.
> removing references to deprecated data module

- public/primitives/http.md
NOTE: The rest of the file uses "request" instead of "req", so I normalized the usage in the full code sample.
> Fix "request" typo in code sample and normalize usage.

- public/guides/local-dev.md
- public/reference/functions/http/node/async.md
This PR fixes the outdated links to the article about sharing code, currently they all lead to a 404 as the file seems to have been renamed to `share-code.md`
> updating link to docs about sharing code

- public/primitives/http.md
i think this change was introduced in arc 6?
> change 'status' to 'statusCode' in body parser response objects example

- public/quickstart/install.md
Added line about how to check Architect version (`arc version`) to Quickstart.
> How to check Architect version (`arc version`) 

- public/primitives/tables.md
Hash key == partition key, with the sort key being optional.
> Rename partition key to sort key

- package-lock.json
- public/primitives/tables.md
- link to core components aws docs
- remove no-longer-existing REPL section
- split out table and index definition into dedicated sections
- update terminology used for keys (partition/sort)
- link to full arc/functions tables reference
- link to ddb stream error handling section.
> variety of db primitive article updates

- src/views/docs/en/reference/app.arc/macros.md
I described macros as being able to add a pre deploy step as they only run when deploying. The link to github is a search for existing macro projects in the architect org.
Thanks again!
> Add some more info about macros to the docs.

- src/views/docs/en/reference/prefs.arc/sandbox-startup.md
- src/views/docs/en/reference/prefs.arc/sandbox.md
- src/views/docs/table-of-contents.js
- move startup script info there.
- add to table of contents.
- clarify where env vars are stored on preferences.arc reference page, link to .env page.
- link up references to cli commands
> add sandbox-startup reference

- src/views/docs/en/guides/developer-experience/using-typescript.md
- src/views/docs/table-of-contents.js
@brianleroux per our discussion in slack. I consider this a draft and am looking for feedback to improve it.
Couple things:
- I put simple but I think clear TypeScript example at https://github.com/activescott/arc-example-typescript and if thought it might be ideal to get that under https://github.com/architect-examples. Then we could reference it from this doc. 
- `npm start` in this repo did kinda render but the css was messed up. So I can see the content but it doesn't look great :) I presume that's not me. Let me know if I missed something.
Let me know if you have ideas to make it better and I'll hack on it when I have a moment (or feel free to push to this branch/PR, I made sure maintainers have edit rights).
-----
> feat: Using TypeScript guide

- src/views/docs/en/guides/developer-experience/logging-and-monitoring.md
It appeared that `showlogs` was a directive rather than a name of the app
Thanks again!
> This was a little confusing

- src/views/docs/en/guides/domains/route53-and-cloudfront.md
AWS now requires aliases used to be entered in the "Alternate Domain Names" field (see https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-cloudfront-distribution.html)
Thanks again!
> Added step 2 bullet for route53 & cloudfront

- src/views/docs/en/guides/extend/plugins.md
- src/views/docs/en/reference/runtime/node.md
Expanded plugin documentation as well as the node runtime docs to describe the new `variables` plugin method we are prototyping for runtime plugin data export purposes, as well as how to load that data when in a Lambda or Sandbox runtime context by expanding on the node runtime docs.
> first stab at service discovery documentation

- src/views/docs/en/reference/runtime/node.md
`_name()` is now called `name()`
Thanks again!
> Update tables _name() method rename

- package.json
- src/http/any-catchall/index.js
- src/http/get-docs-000lang-catchall/highlighter.js
- test/sandbox-http-test.js
Use `@arcitect/asap` in lieu of `@architect/functions http.proxy` for static playground proxy in catchall.  
This became an issue when [functions was updated to ^4.0.0](https://github.com/architect/arc.codes/commit/a3529a50785920dbf8c6241a828ba77fed097e99#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R41) from 3.4.12
Also add a quick Sandbox HTTP smoke test.
Bonus: update call to highlight.js#highlight method to avoid deprecation notices per [this issue](https://github.com/highlightjs/highlight.js/issues/2277)
---
Please also be sure to completed the CLA as it's required for your PR to be merged. A github comment will prompt you if …
> Use @architect/asap in catchall for static playground proxy

- scripts/dictionary.js
- src/views/docs/en/guides/extend/plugins.md
Confirmed it's `esbuild` and not any other capitalization
Thanks again!
> Add arc-plugin-esbuild to the list of plugins

- .github/pull_request_template.md
It is now `main`
Thanks again!
> fix: pull request template references master

- public/css/index.css
- src/views/modules/components/sidebar.js
Switch to using the details/summary tag for keyboard navigation.
> Issue #382: Registrars menu is not keyboard accessible

- public/css/syntax.css
This PR adds some CSS to provide a background and border color for inline code blocks. I'm not married to the border, color, radius, etc but this is a good starting point.
It turns:
into:
> 💄  Background color for inline code blocks

- public/css/syntax.css
- public/static.json
to prevent overlap and tone down overall contrast
before:  
updated:  
I think there is still not enough contrast in `a:has(code)` but I couldn't get it to target correctly on my first pass
> tweak inline code

- src/views/docs/en/guides/backend/events-and-queues.md
- src/views/docs/en/guides/extend/custom-iam-roles.md
- src/views/docs/en/guides/get-started/detailed-aws-setup.md
- src/views/docs/en/reference/app.arc/aws.md
- src/views/docs/en/reference/config.arc/aws.md
Fix for Issue #399 
Updates default nodejs runtime to 14.x in docs.
> Issue Docs don't agree on default node runtime #399

- src/views/docs/en/guides/backend/persist-data.md
- src/views/docs/en/guides/extend/add-a-custom-domain.md
- src/views/docs/en/guides/extend/plugins.md
- src/views/docs/en/guides/frontend/http-functions.md
- src/views/docs/en/guides/frontend/single-page-apps.md
- src/views/docs/en/guides/frontend/static-assets.md
- src/views/docs/en/guides/frontend/web-sockets.md
- src/views/docs/en/reference/app.arc/static.md
- src/views/docs/en/reference/cli/hydrate.md
Addresses #248 by linking from app.arc > @static to the frontend guide on Static Assets. Also clarifies that the `/public` directory lives at the project root.
> link to static assets guide from app.arc static reference

- .github/workflows/link-checker.yaml
- package.json
- scripts/link-checker-test.js
- src/shared/redirect-map.js
- src/views/docs/en/about/upgrade-guide.md
- src/views/docs/en/reference/cli/env.md
- src/views/docs/en/reference/configuration/local-preferences.md
- test/backend/sandbox-http-test.js
I used linkinator locally to test for bad links, but thought it might make for a good test programatically.
~~Still working on it.~~
This works best as a GitHub CI Action. (originally a part of the test suite)
- It's a bit slow. Takes the HTTP test from <1s to ~ 8s (fine in GH Actions)
- it doesn't report 301/2 redirects -- so it can't test if docs use outdated links, just busted ones.
- it adds 98kB (maybe less because shared dependencies)
- it helped find ~8 broken links and will help a ton when updating doc file structure
> add test for broken links with linkinator

- package.json
- public/css/index.css
- public/index.js
- public/static.json
- src/http/get-docs-000lang-catchall/index.js
- src/views/modules/document/html.js
This PR adds a right rail into the docs which contains a table of contents for the page. 
Right now the toc includes all the h2, h3, h4, h5 and h6 headers on the page. I can leave it like this or reduce the toc to just the h2 and h3 tags. I know some sites limit how deep the toc goes.
It removes the package `markdown-it-anchor` and replaces it with `markdown-it-toc-and-anchor` which serves the dual purpose of adding anchors creating the toc. I created a `slugify` method so that the slugs would not change between `markdown-it-anchor` and `markdown-it-toc-and-anchor`. I actually prefer the `markdown-it-toc-and-anchor` slugs but it would necessitate changing all our current in page links and possibly break bookmarks so I went with a custom `slugify`.
I am more than happy to make UI tweaks, I …
> Right rail page table of contents

- src/views/docs/en/reference/runtime-helpers/node.js.md
This is a small change to clarify using the asap function in the async middleware pattern. 
In the docs it includes these two examples but the asap is different in each. Calling asap returns a handler so in the first example asap is that factory function and in the second example it is the handler that is returned (not sure if that terminology is exactly correct). Either way it is confusing. There may be a different way to clear it up that would be better. 
This is how it is currently shown in the docs. 
------
```javascript
// basic usage
let asap = require('@architect/asap')
let params = { cacheControl: 'max-age=0' }
exports.handler = asap(params)
```
```javascript
// asap as arc.http.async middleware
let arc = require('@architect/functions')
let asap = require('@architect/asap')() …
```
> clarify asap docs

- src/views/docs/en/get-started/detailed-aws-setup.md
- src/views/docs/en/get-started/quickstart.md
- src/views/docs/en/guides/backend/events-and-queues.md
- src/views/docs/en/guides/frontend/middleware.md
- src/views/docs/en/guides/frontend/single-page-apps.md
- src/views/docs/en/reference/cli/init.md
The docs say `npm init @architect new-app` but that does not work, because [`npm init`](https://docs.npmjs.com/cli/v8/commands/npm-init) will try to run `@architect/create-new-app`.
`npm init @architect` will call `@architect/create`, but once you add something after it, it looks for `create-<thing>`.
I had to use `npm exec @architect/create new-app` to get it to create a folder called `new-app`. Updating the docs with the correct instruction. Also using `your-app` so it's clear that `new-app` is not some kind of keyword.
> Correct quickstart instructions

- package.json
- public/index.js
- public/static.json
- scripts/dictionary.txt
- src/http/get-docs-000lang-catchall/index.js
- src/views/docs/en/get-started/quickstart.md
- src/views/docs/en/guides/developer-experience/custom-source-paths.md
- src/views/docs/en/reference/configuration/local-preferences.md
- src/views/docs/en/reference/runtime-helpers/deno.md
- src/views/docs/en/reference/runtime-helpers/node.js.md
- src/views/docs/en/reference/runtime-helpers/python.md
- src/views/docs/en/reference/runtime-helpers/ruby.md
- src/views/modules/components/document-outline.js
- src/views/modules/document/html.js
lots of hierarchy adjustment and rewording headings
add docs for `arc.ws`, `.tables`, and others
a few other small changes divided into separate commits with updates to deps and improvements for the document outline
<details open>
<summary>Preview</summary>
The page is too long for Firefox to correctly capture 😧 
</details>
> Node.js Runtime Helpers (aka architect/functions) doc update

- package.json
- src/views/docs/en/guides/developer-experience/local-development.md
On occasion new users are unsure of local prereqs. Is this a good place for now?
In #411 I think this fits into "App Development Guide" > "Working Locally" and/or "Home" > "Installation"
fixes #456
> add requirements to local development doc

- package.json
- src/http/get-docs-000lang-catchall/index.js
- src/http/get-docs-000lang-catchall/renderer.js
- test/backend/renderer-test.js
move renderer to separate, testable file. the main index.js was getting a bit long
also, I opted for the `front-matter` lib to cut down on complexity.
> Abstract out renderer

- src/views/docs/en/guides/developer-experience/using-typescript.md
Link to `@architect/functions` reference page was pointing to `localhost:3333`.
> fix broken link in `Using TypeScript` docs

- package-lock.json
- package.json
- src/shared/redirect-map.js
- src/views/docs/en/guides/developer-experience/sharing-code.md
- src/views/docs/en/reference/project-manifest/shared.md
- src/views/docs/en/reference/project-manifest/views.md
This expands the Sharing Code doc. I leaned toward over-explaining, so let me know if it's too heavy-handed.
This doesn't address sharing code in Typescript. That's for another PR
> update sharing code, shared, and views docs

- src/views/docs/en/get-started/detailed-aws-setup.md
Follow up from issue [#1311](https://github.com/architect/architect/issues/1311)
Since Architect doesn't support using an EC2 IAM role to
authenticate AWS API calls, and adding support would require
big changes to core functionality, adding a note to the
documentation can help the occasional dev who finds themself
needing using this form of authentication.
Since this is principally an example of how to handle a particular
form of authentication, I included it in the section on setting
up AWS credentials. I made the example as simple as I could,
and wrote it in JS, because that's the language I'm using, so
it's the one that I've actually tested and seen work.
To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the …
> Add guide on AWS authentication via EC2 IAM role

- .github/workflows/link-checker.yaml
- src/views/docs/en/guides/developer-experience/sharing-code.md
- src/views/docs/en/guides/developer-experience/using-deno.md
- src/views/docs/table-of-contents.mjs
Describe current status of Deno support.
I deliberately didn't include `deno` in `@aws: { runtime: }` docs yet since there are still some serious caveats, namely the default layer and the performance cost.
> start new "Using Deno" doc 🦕

- src/views/docs/en/reference/project-manifest/plugins.md
Initial `#` links on the`@plugins` Project Manifest page where pointing to the current page instead of the intended Plugins Overview page.
Thanks again!
> Pointing links to correct page

- package.json
Our build wasn't working because our GitHub action is setup to use Node LTS. As of Feb 1st, 2023 the LTS version of Node uses npm 9.3.1 or greater. Our package.json was set to use npm 8.5.0 or later and npm less than 9.0.0. This commit changes the package.json to allow npm 9.
> Bump acceptable npm version

- src/views/docs/en/reference/configuration/function-config.md
- src/views/docs/en/reference/project-manifest/aws.md
Noticed 14.x and x86 are mentioned as defaults still in the documentation. Creating a fresh project and deployed to confirm it should be 16.x and arm64 and updated all the references I could find.
Not sure if 18.x should be worked in some of these references too, but felt that veered more in to stylistic that basic correction at this stage.
> Update defaults for Node.js versions and architecture

- src/views/docs/en/reference/project-manifest/aws.md
Ref: https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/
I was researching the support for AWS Lambda Node 20 and decided to make a small update to the AWS `runtime` section of the Project Manifest documentation since I was already checking when the support will be available for Architect.
> Add Node 20 as a runtime option in AWS

- src/views/docs/en/about/upgrade-guide.md
- src/views/docs/en/reference/project-manifest/aws.md
As per my comment on [this issue](https://github.com/architect/architect/issues/1297#issuecomment-1829933174), I'm adding some documentation that support of the REST API type in API Gateway has been moved to a plugin.
> Mention removal of built-in API Gateway REST support

- src/views/docs/en/reference/configuration/function-config.md
Expanded the example and added a line about enclosing scoped dependency names in quotes to avoid the almighty wrath of the parser.
> Add detail for scoped dependency names and `ignoredDependencies`

- src/views/docs/en/reference/project-manifest/events.md
- src/views/docs/en/reference/project-manifest/http.md
- src/views/docs/en/reference/project-manifest/proxy.md
- src/views/docs/en/reference/project-manifest/queues.md
- src/views/docs/en/reference/project-manifest/scheduled.md
- src/views/docs/en/reference/project-manifest/ws.md
Firstly there were a couple of <arc-viewer> elements that needed closed (spotted by @ryanblock)
Second, the directory outputs were a little off, and inconsistent.
Finally, I felt like it needed to be explicit that the scaffolding is only generated when `arc create` is run.
> fix `arc create` output in project-manifest docs

- src/views/docs/en/about/upgrade-guide.md
only use path for links so that links work on staging. fixes #597
> fix link to plugin docs in old upgrade guide

- src/views/docs/en/reference/configuration/function-config.md
relates to architect/architect#1476
> docs: call out that `ignoreDependencies` does not work for `shared` dependencies

- src/views/docs/en/guides/developer-experience/dependency-management.md
- src/views/docs/en/guides/developer-experience/sharing-code.md
relates to architect/architect#1462
tested out in sandbox, at least
> fix: wrong import syntax used in python examples

- src/views/docs/en/guides/plugins/overview.md
also referencing that .mjs files are ok for plugin authoring
> docs: updating and linking the plugins overview page
