architect/arc.codes

- src/shared/en/aws/guides-offline.md
was: test/*-test.js
now: tests/*-test.js
> fix path for test script

- src/shared/en/aws/guides-cors.md
Pretty sure this was meant to be domains. If not I've got FOMO over Fomains.
> Fixing a typo.

- CODE_OF_CONDUCT.md
- src/shared/en/aws/guides-cors.md
- src/shared/en/aws/guides-custom-dns.md
- src/shared/en/aws/quickstart.md
- src/shared/en/aws/reference.md
> Use HTTPS everywhere we can

- src/shared/en/aws/reference-queues.md
> Updating docs on queues section to show code is generated in queues dir

- src/shared/en/aws/reference-data-update.md
Hello, I am using architect for a few projects and am really impressed with what you have built here. This is an amazing tool which helps a frontend focused dev like myself quickly setup a solid serverless backend. Thanks so much for building and open sourcing all this fantastic stuff. I love the latest documentation, all these examples make it so much clearer how to work with DynamodB via architect. I needed to add that SET expression in order to get my copy pasted version of this example working.
Thank you!
> add SET to the UpdateExpression

- src/shared/en/aws/guides-data.md
I believe these are the correct paths, if not, then I'm worried 'cause I never have a `src/html/` path in my arc apps....
> 📝 Fix reference to file paths in data guide

- src/shared/en/aws/guides-data.md
Using the right variable names, I think. Either this or we pass the variable in as the old name (`path`) from `layout.js` correctly (currently passes it in as `url`).
> Updating variable refs in _header in data guide

- dictionary.js
- src/shared/en/aws/quickstart.md
Replace 'Control Panel' instructions.
> Add powershell version of environment variables

- src/shared/en/aws/guides-background-tasks.md
> fix typo in background task guide

- src/shared/en/aws/guides-data.md
> Remove trailing 'f' from data guide

- src/shared/en/aws/intro-limits.md
- src/shared/en/aws/reference-arc-config.md
Mention lambdas are 5 seconds by default, add link to npx config to change
> Add some more detail to timeouts

- src/shared/en/aws/reference-aws.md
Documents https://github.com/arc-repos/architect/pull/308
> add docs for custom runtimes

- src/shared/en/aws/guides-background-tasks.md
- src/shared/en/aws/guides-data.md
- src/shared/en/aws/guides-upgrade.md
- src/shared/en/aws/index.md
Hi 😀 
This is primarily a fix to the markdown that is currently incorrectly rendering at the bottom of the [index page](https://arc.codes/). Adding the newline before the closing code fence resolved the render issue.
I have also included a few other documentation related tweaks. 
Let me know if you'd prefer these as separate pull requests.
> Documentation updates

- public/primitives/cdn.md
Hi. Just stumbled upon that one.
> Add missing word

- .arc
- package-lock.json
- public/intro/playground.js
- src/http/get-playground/.arc-config
- src/http/get-playground/index.js
- [ x ] Forked the repo and created your branch from `master`
- [ x ] Made sure tests pass (run `npm it` from the repo root)
Thanks again!
> Playground

- public/primitives/tables.md
- scripts/dictionary.js
> encryption docs

- public/primitives/tables.md
- scripts/dictionary.js
> add docs for dynamo ttl

- public/primitives/tables.md
> add docs for point in time recovery

- public/guides/testing.md
> docs: Fixes typos on testing guide

- public/index.md
> Aligned with Architect 6.3.4's actual output

- public/reference/arc/tables.md
- Remove old syntax
- link to app primitives page that has a ton more info
> Update the tables reference lambda/streaming info

- .github/pull_request_template.md
It’s now a bit more relevant to this particular repo.
> Cleanup the PR template

- .github/contributing.md
Fixes the code of conduct link in contributing.md
> Fix the code of conduct link

- public/guides/upgrade.md
Fixed a bad link in the upgrade guide
> Fix arc6 missing dns issue link

- public/reference/functions/http/node/classic.md
> changing typo in example code

- public/primitives/http.md
> Add missing 's' to exports

- public/reference/cli/env.md
> `arc env verify` doesn't exist

- public/reference/functions/events.md
- public/reference/functions/queues.md
- public/reference/functions/static.md
- public/reference/functions/ws.md
- [X ] Forked the repo and created your branch from `master`
Thanks again!
> Fix typos in @architect/functions documentation

- public/reference/cli/destroy.md
- src/http/get-index/index.js
- src/http/get-index/toc.md
> adding `arc destroy` reference article.

- src/views/modules/components/github-link.js
- src/views/modules/components/slack-link.js
- src/views/modules/document/html.js
> adds aria-label to chill out chromes

- package.json
- src/views/modules/.eslintrc.js
- src/views/modules/components/sidebar.js
- src/views/modules/layouts/one-column.js
- src/views/modules/layouts/two-column.js
- src/views/modules/pages/main.js
> Lint that esm

- src/views/docs/idk/architect-project-structure/databases/tables.md
> remove REPL docs; RIP REPL

- src/views/docs/en/guides/get-started/project-layout.md
Fixes a tiny typo in the docs.
> Fix typo in project-layout.md

- src/views/docs/en/reference/runtime/node.md
> Add missing await keyword

- src/views/docs/en/guides/get-started/project-layout.md
Fixed a few broken links
Thanks again!
> Fix link to static and ws docs

- src/views/docs/en/guides/get-started/project-layout.md
> Fixes the link to the web services documentation

- src/views/docs/en/guides/get-started/project-layout.md
> Fixes link to `@static` documentation

- src/views/docs/en/reference/runtime/node.md
This updates some of the arc.codes docs to reflect what I find to be reality and consistent with source :)
-----
- [+] Forked the repo and created your branch from `master`
- [+] Made sure tests pass (run `npm it` from the repo root)
- [+] Updated relevant documentation internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
- [+] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes
> docs: clarify documentation for arc.tables facade and arc.tables._name

- src/views/modules/document/head.js
Fixed meta tags so that social media cards will show for a better marketing experience.
> Fixed meta tags so that social media cards will show for a better marketing experience.

- public/reference/cli/sandbox.md
Most of these features already existed in the sandbox, but this adds the scheduled events as well
Relates to https://github.com/architect/sandbox/pull/466
> More sandbox instructions, scheduled events info

- src/views/docs/en/reference/app.arc/indexes.md
This is related to the new featured added by @anatomic: named indexes. See architect/architect#974
> adding documentation for named indexes

- src/views/docs/en/guides/extend/architect-plugins.md
- src/views/docs/table-of-contents.js
This is related to architect/architect#1062.
This PR covers the plugin author-facing documentation. The interfaces a plugin author must implement, along with examples where relevant.
Currently this is a draft PR - I would not merge until all the other supporting pieces in all other architect modules pass review and are merged.
> Plugin Docs

- src/views/docs/en/guides/extend/architect-plugins.md
I somehow copy-pasted the one snippet that was wrong 😆
Thanks again!
> Fix package function signiture

- src/views/docs/en/guides/domains/dreamhost.md
- src/views/docs/table-of-contents.js
Added Dreamhost domains guide to docs.
> Added Dreamhost domains guide to docs

- package.json
- src/views/docs/en/guides/domains/dreamhost.md
- src/views/docs/en/guides/domains/godaddy.md
- src/views/docs/en/guides/domains/namecheap.md
- src/views/docs/en/guides/domains/one.md
- src/views/docs/table-of-contents.js
Added documentation for the following domain registrars:
- Godaddy
- Namecheap
- One
> Added docs for new domain registrars

- src/views/docs/en/reference/cli/destroy.md
- link to other commands / app.arc references
- add new --no-timeout flag docs.
> improve destroy cli docs

- src/views/docs/en/reference/app.arc/views.md
> fix bad link

- src/views/docs/en/guides/developer-experience/dependency-management.md
- src/views/docs/en/reference/app.arc/ws.md
> Fix BrokenFix broken links in docs

- src/views/docs/en/guides/extend/plugins.md
> fix broken links

- scripts/dictionary.js
- src/views/docs/en/reference/runtime/node.js.md
> Minor update to auth middleware example.

- src/http/get-docs-000lang-catchall/markdown-class-mappings.js
- src/views/docs/en/guides/backend/scheduled-functions.md
- src/views/docs/en/guides/developer-experience/sharing-code.md
- src/views/docs/en/guides/extend/plugins.md
- src/views/docs/en/guides/frontend/middleware.md
- src/views/docs/en/reference/app.arc/ws.md
1. Fix word break in table cells
1. Remove fixed table layout for adaptive column width
1. Normalize Markdown table formatting across docs -- for editing, no effect on HTML output
Before:
After:
---
> Markdown tables -> Styled HTML tables

- package.json
- src/views/package.json
views is written with ESM so dependencies weren't optimized from the root package. so create a package.json in views for now.
---
Thanks again!
> move slugify dep to views

- src/views/docs/en/reference/config.arc/policies.md
> Update policies configuration docs

- src/views/docs/en/guides/domains/overview.md
Links to domain registrars all had an invalid path. #386
> Corrected invalid links

- public/css/index.css
- public/css/styles.css
- public/static.json
- src/views/modules/components/sidebar.js
- src/views/modules/document/html.js
- src/views/modules/layouts/two-column.js
Temporarily adding a banner to highlight the fact we are moving to Discord.
> 🖼️  Add Discord announcement banner

- .github/workflows/woke.yaml
Adds an inclusive language check to pull requests. 
See issue #391 for details.
> Issue #391: Add inclusive language check to PR's

- public/components/arc-viewer.js
- public/css/styles.css
- public/static.json
Based upon what I learned from @kristoferjoseph lunch n' learn 👍
> 🔥  Remove arc--tab-btn class

- public/css/docsearch.css
- public/static.json
- src/http/get-docs-000lang-catchall/index.js
- src/views/modules/components/algolia.js
- src/views/modules/components/search.js
- src/views/modules/document/head.js
- src/views/modules/document/html.js
- src/views/modules/document/top-nav.js
* hooked up to Algolia's index of arc.codes
* added Search component
* added Search to topbar
* added boilerplate style customization CSS to docsearch.css -- commented out for now
> add Algolia Docsearch

- .github/workflows/build.yml
> Discord notifications for build and deploy

- scripts/dictionary.txt
- src/views/docs/en/guides/get-started/detailed-aws-setup.md
- src/views/docs/en/reference/configuration/function-config.md
- src/views/docs/en/reference/project-manifest/aws.md
- src/views/docs/en/reference/runtime-helpers/deno.md
- src/views/docs/table-of-contents.js
- Rearrange and update "Detailed AWS setup" doc
- Update @aws doc
- Update Function Config doc
- Update Deno doc/statement
edit: remove outdated screenshots, best reviewed in a browser :) 
Fixes #442
> Runtime docs with new aliases

- src/views/docs/en/guides/frontend/static-assets.md
This example returns JSON instead of the html we intend.
Thanks again!
> fix: old function return

- package.json
It doesn't look like we need this package anymore. Please confirm.
Signed-off-by: Simon MacDonald <simon.macdonald@gmail.com>
> Remove onigasm

- src/views/docs/en/reference/project-manifest/http.md
fixes https://github.com/architect/architect/issues/1281
> Update http doc with any, head, and options

- src/views/docs/en/reference/cli/sandbox.md
> sandbox + Monterey callout

- src/views/docs/en/reference/runtime-helpers/node.js.md
Coming from little experience with DynamoDB's client lib, I thought it might be helpful to provide an example with the full CRUD loop for data items.
For ease, here's the example text...
---
Given the following `app.arc` file:
```arc
@app
people-app
@tables
people
email *String
@tables-indexes
people
job *String
name peopleByJob
```
A data access layer will be generated like so:
```javascript
let arc = require('@architect/functions')
let client = await arc.tables()
let people = client.people
// create Chuck and Jana
let chuck = await people.put({
email: 'chuck@example.com',
job: 'Web Developer',
age: 35,
})
let jana = await people.put({
email: 'jana@example.com',
job: 'Web Developer',
age: 64,
})
// increment Jana's age
await people.update({
Key: { email: jana.email }, …
```
> improve the arc/functions tables example

- src/views/docs/en/:tutorials/configuring-aws.md
- src/views/docs/en/introduction.md
populating unlinked docs. progress toward #411
> Populate new docs

- src/views/docs/en/get-started/detailed-aws-setup.md
grammar fix to AWS credentials section of AWS setup instructions
Thanks again!
> correction to credential setup instructions

- src/views/modules/document/ga.js
- src/views/modules/document/html.js
Signed-off-by: macdonst <simon.macdonald@gmail.com>
Thanks again!
> Add GoogleAnalytics to arc.codes

- .github/workflows/woke.yaml
- scripts/dictionary.txt
- src/views/docs/en/guides/developer-experience/dependency-management.md
- src/views/docs/en/reference/cli/destroy.md
- src/views/docs/en/reference/runtime-helpers/ruby.md
these changes are the result of some tinkering Brian and I did getting Ruby deployed with Arc, specifically with Bundler + `architect-functions` gem
> Ruby: clarify steps for deployment with bundler onboard

- scripts/dictionary.txt
- src/views/docs/en/guides/developer-experience/using-esm.md
- src/views/docs/table-of-contents.js
> add using esm doc

- readme.md
- src/views/docs/en/guides/developer-experience/local-development.md
- src/views/docs/en/guides/developer-experience/using-typescript.md
- src/views/docs/en/guides/extend/plugins.md
- src/views/docs/en/reference/cli/env.md
- src/views/docs/en/reference/cli/sandbox.md
- src/views/docs/en/reference/configuration/function-config.md
- src/views/docs/en/reference/configuration/local-preferences.md
- src/views/docs/en/reference/project-manifest/aws.md
- src/views/docs/en/reference/project-manifest/shared.md
- src/views/docs/en/reference/project-manifest/views.md
> Expand function config doc

- scripts/dist.sh
- scripts/highlight/index.js
- src/views/docs/en/about/contribute.md
- src/views/docs/en/get-started/project-manifest.md
- src/views/docs/en/get-started/why-architect.md
- src/views/docs/en/guides/developer-experience/custom-source-paths.md
- src/views/docs/en/introduction.md
- src/views/docs/en/reference/project-manifest/app.md
- src/views/docs/en/reference/project-manifest/aws.md
- src/views/docs/en/reference/project-manifest/events.md
- src/views/docs/en/reference/project-manifest/http.md
- src/views/docs/en/reference/project-manifest/macros.md
- src/views/docs/en/reference/project-manifest/proxy.md
- src/views/docs/en/reference/project-manifest/queues.md
- src/views/docs/en/reference/project-manifest/scheduled.md
- src/views/docs/en/reference/project-manifest/shared.md
- src/views/docs/en/reference/project-manifest/static.md
- src/views/docs/en/reference/project-manifest/tables-indexes.md
- src/views/docs/en/reference/project-manifest/tables-streams.md
- src/views/docs/en/reference/project-manifest/tables.md
- src/views/docs/en/reference/project-manifest/views.md
- src/views/docs/en/reference/project-manifest/ws.md
> remove TOML references and .ini highlighting

- src/views/docs/en/about/community.md
Signed-off-by: macdonst <simon.macdonald@gmail.com>
> Community Call

- src/shared/redirect-map.js
- src/views/docs/en/reference/cli/sandbox.md
- src/views/docs/en/reference/configuration/local-preferences.md
> add livereload to sandbox docs

- package-lock.json
- package.json
> update deps to latest

- package-lock.json
- package.json
- src/views/docs/en/guides/frontend/sessions.md
- src/views/docs/en/reference/runtime-helpers/node.js.md
- src/views/docs/table-of-contents.js
~~I still need to get database-backed sessions working locally in order to test and update the related docs.~~
Update existing sessions guide and omit database-backed sessions section (currently [not working as intended](https://github.com/architect/functions/blob/18c172b5d96ed799763048e8645634f80e595ebc/src/http/session/providers/ddb/index.js#L84))
> update and publish sessions doc

- src/views/docs/en/guides/developer-experience/using-typescript.md
add shared code and example project
> Update Using Typescript

- package-lock.json
- package.json
- src/views/docs/en/reference/configuration/function-config.md
- src/views/docs/en/reference/project-manifest/aws.md
- src/views/modules/document/head.js
- src/views/modules/document/script.js
document new `@aws` `storage` property
and bump a couple dependencies, fix minimist vulnerability, and use arc.static
> document aws storage property

- src/views/docs/en/reference/configuration/local-preferences.md
> Document `@sandbox` > `ports` in Local prefs

- package-lock.json
- package.json
- src/views/docs/en/guides/frontend/static-assets.md
- src/views/docs/en/reference/project-manifest/static.md
- document `@static`'s `prefix`, `prune`, and `spa` options
- rearrange a bit
- update arc/fns
> add missing `@static` properties

- package-lock.json
- src/views/docs/en/about/contribute.md
> Update contributor guide

- src/views/docs/en/reference/configuration/function-config.md
> Document @aws SQS fifo option

- scripts/dictionary.txt
- src/views/docs/en/guides/developer-experience/continuous-integration/github-actions.md
- src/views/docs/en/guides/developer-experience/continuous-integration/gitlab-pipelines.md
- src/views/docs/table-of-contents.mjs
> add GitLab ci/cd doc

- src/views/docs/en/reference/runtime-helpers/node.js.md
-~[ ]~ Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes
Thanks again!
> docs: fix links for methods in the nodejs helper

- src/views/docs/en/guides/frontend/sessions.md
- src/views/docs/en/reference/cli/env.md
See https://github.com/architect/arc.codes/issues/544
Thanks again!
> Document ARC_APP_SECRET min length

- src/views/docs/en/guides/developer-experience/continuous-integration/github-actions.md
> Fix typo in example Github Actions config file

- src/views/docs/en/reference/cli/sandbox.md
Relates to https://github.com/architect/sandbox/pull/678
> Adds documentation for host param

- package-lock.json
- package.json
- src/views/docs/en/guides/plugins/set.md
- src/views/docs/en/reference/project-manifest/static.md
> Arc 10.4 docs

- src/views/docs/en/about/upgrade-guide.md
> Small typo on arc 9->10 upgrade guide

- src/views/docs/en/guides/plugins/hydrate.md
- src/views/docs/en/guides/plugins/set.md
- src/views/docs/table-of-contents.mjs
> Hydrate plugins

- src/views/docs/en/reference/project-manifest/aws.md
Just a minor typo fix ✏️ 
Thanks again!
> Fix minor "scrath" typo in aws pragma doc

- src/views/docs/en/reference/project-manifest/indexes.md
(relates to architect/architect#1083)
⚠️ This should not be merged until https://github.com/architect/package/pull/145 is merged and released.
> Adding documentation for index projections

- package-lock.json
- package.json
- src/views/docs/en/reference/cli/sandbox.md
- src/views/docs/en/reference/runtime-helpers/node.js.md
> Add details of the new `arc.http` `compression` property

- package-lock.json
- package.json
- src/views/docs/en/guides/plugins/create.md
- src/views/docs/en/guides/plugins/overview.md
- src/views/docs/en/guides/plugins/set.md
- src/views/docs/table-of-contents.mjs
> Compiled runtimes

- src/views/docs/en/reference/cli/sandbox.md
It seems to only work with the all caps version
Thanks again!
> fix typo useAWS over useAws

- package-lock.json
- package.json
- public/css/styles.css
- public/css/syntax.css
- src/http/get-docs-000lang-catchall/index.mjs
- src/http/get-docs-000lang-catchall/markdown-class-mappings.mjs
- src/views/modules/components/sidebar.mjs
- src/views/modules/document/html.mjs
> Headers / links

- src/views/docs/en/reference/runtime-helpers/python.md
> Fix broken link

- src/views/docs/en/guides/frontend/static-assets.md
- src/views/docs/en/reference/project-manifest/static.md
Thanks again!
https://github.com/architect/architect/issues/1106 where I saw this feature
#501 
closes https://github.com/architect/architect/issues/1396
> Add documentation about `fingerprint external`

- package-lock.json
- src/views/docs/en/about/contribute.md
- src/views/docs/en/about/upgrade-guide.md
- src/views/docs/en/get-started/detailed-aws-setup.md
- src/views/docs/en/get-started/project-manifest.md
- src/views/docs/en/guides/backend/event-functions.md
- src/views/docs/en/guides/backend/persist-data.md
- src/views/docs/en/guides/backend/queue-functions.md
- src/views/docs/en/guides/extend/plugins.md
- src/views/docs/en/guides/frontend/websocket-functions.md
- src/views/docs/en/guides/plugins/inventory.md
- src/views/docs/en/reference/cli/deploy.md
- src/views/docs/en/reference/configuration/function-config.md
- src/views/docs/en/reference/project-manifest/aws.md
- src/views/docs/en/reference/project-manifest/ws.md
- src/views/docs/en/reference/runtime-helpers/node.js.md
> `aws-lite`

- src/views/docs/en/reference/project-manifest/tables-indexes.md
related to architect/architect#1394
> docs: important callouts when creating or deleting table indexes

- scripts/dictionary.txt
- src/views/docs/en/reference/cli/deploy.md
- src/views/docs/en/reference/cli/destroy.md
- src/views/docs/en/reference/cli/env.md
- src/views/docs/en/reference/cli/hydrate.md
- src/views/docs/en/reference/cli/init.md
- src/views/docs/en/reference/cli/logs.md
- src/views/docs/en/reference/cli/sandbox.md
- src/views/docs/en/reference/configuration/function-config.md
- src/views/docs/en/reference/configuration/local-preferences.md
To be paired with work in https://github.com/architect/architect/pull/1507
> docs: updating/maintenance of CLI command docs
